# waypoints.yaml

waypoints:
  - [0.0, 0.0, 1.5]   # 起飞点
  - [1.0, 0.0, 1.5]   # 向前飞
  - [1.0, 1.0, 1.5]   # 向右飞
  - [0.0, 1.0, 1.5]   # 回到左边
  - [0.0, 0.0, 1.5]   # 回到起点
  - [0.0, 0.0, 1.0]   # 回到起点
  - [0.0, 0.0, 0.5]   # 回到起点
  - [0.0, 0.0, 0.0]   # 回到起点
